# Generated by Django 5.0 on 2025-09-22 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("preferred_name", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("summary", models.TextField()),
                ("technical_skills", models.TextField(blank=True)),
                ("soft_skills", models.TextField(blank=True)),
                ("degree", models.CharField(blank=True, max_length=100)),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("graduation_year", models.IntegerField(blank=True, null=True)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("current_job", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("experience_years", models.CharField(blank=True, max_length=20)),
                ("availability", models.CharField(blank=True, max_length=20)),
                ("languages", models.CharField(blank=True, max_length=200)),
                ("certifications", models.TextField(blank=True)),
                ("portfolio", models.URLField(blank=True)),
                ("salary_expectation", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
