# Generated by Django 5.0 on 2025-09-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employer_jobseeker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
