# Generated by Django 5.0 on 2025-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_jobseekerprofile_show_availability_to_recruiters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='show_phone_to_recruiters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='show_salary_expectation_to_recruiters',
            field=models.BooleanField(default=True),
        ),
    ]
