# Generated by Django 5.0 on 2025-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_jobseekerprofile_show_phone_to_recruiters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_email_to_recruiters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_secondary_email_to_recruiters',
            field=models.BooleanField(default=False),
        ),
    ]
