# Generated by Django 5.0 on 2025-10-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employerprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_email_to_recruiters',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='show_secondary_email_to_recruiters',
        ),
    ]
