# Generated by Django 5.0 on 2025-10-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_jobseekerprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='secondary_email',
        ),
    ]
