# Generated by Django 5.0 on 2025-11-21 01:24

from django.db import migrations, models


def migrate_location_data(apps, schema_editor):
    """Migrate existing location data to new address, city, state fields"""
    JobSeekerProfile = apps.get_model('accounts', 'JobSeekerProfile')
    
    for profile in JobSeekerProfile.objects.all():
        if profile.location:
            location = profile.location.strip()
            if location:
                # Try to parse "City, State" format
                if ',' in location:
                    parts = [p.strip() for p in location.split(',')]
                    if len(parts) >= 2:
                        # Assume last part is state, everything before is city/address
                        profile.state = parts[-1]
                        if len(parts) == 2:
                            # "City, State" format
                            profile.city = parts[0]
                        else:
                            # "Address, City, State" format
                            profile.address = ', '.join(parts[:-2])
                            profile.city = parts[-2]
                    else:
                        # Just one part, put it in city
                        profile.city = location
                else:
                    # No comma, assume it's a city
                    profile.city = location
                profile.save()


def reverse_migrate_location_data(apps, schema_editor):
    """Reverse migration - combine address, city, state back to location"""
    JobSeekerProfile = apps.get_model('accounts', 'JobSeekerProfile')
    
    for profile in JobSeekerProfile.objects.all():
        parts = []
        if profile.address:
            parts.append(profile.address)
        if profile.city:
            parts.append(profile.city)
        if profile.state:
            parts.append(profile.state)
        if parts:
            profile.location = ', '.join(parts)
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_employerprofile_email_and_more"),
    ]

    operations = [
        # Step 1: Add new fields
        migrations.AddField(
            model_name="jobseekerprofile",
            name="address",
            field=models.CharField(
                blank=True, help_text="Street address", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        # Step 2: Migrate data from location to new fields
        migrations.RunPython(migrate_location_data, reverse_migrate_location_data),
        # Step 3: Remove old location field
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="location",
        ),
    ]
