# Generated by Django 5.0 on 2025-11-21 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_employerprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Saved Search', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='accounts.employerprofile')),
            ],
        ),
    ]

