# Generated by Django 5.0 on 2025-11-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_savedsearch'),
        ('accounts', '0011_split_location_field'),
    ]

    operations = [
    ]
