# Generated by Django 5.0 on 2025-11-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_split_location_field"),
        ("accounts", "0012_savedsearch"),
    ]

    operations = []
