# Generated by Django 5.0 on 2025-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobpostings", "0002_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="ZIP/Postal code", max_length=10
            ),
        ),
    ]
