# Generated by Django 5.0 on 2025-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobpostings", "0003_jobposting_zip_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="location",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="state",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
