# Generated by Django 5.0 on 2025-09-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0004_remove_jobposting_location_jobposting_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
