# Generated by Django 5.0 on 2025-10-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobpostings", "0005_alter_jobposting_city_alter_jobposting_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="address",
            field=models.CharField(blank=True, help_text="Address", max_length=10),
        ),
    ]
