# Generated by Django 5.0 on 2025-10-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobpostings", "0006_remove_jobposting_zip_code_jobposting_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="address",
            field=models.CharField(blank=True, help_text="Address", max_length=50),
        ),
    ]
