# Generated by Django 5.0 on 2025-10-23 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0007_alter_jobposting_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for the stage', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of stages in the pipeline')),
                ('is_final_positive', models.BooleanField(default=False, help_text='Is this a final positive outcome?')),
                ('is_final_negative', models.BooleanField(default=False, help_text='Is this a final negative outcome?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this application'),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the pipeline stage was last updated'),
        ),
        migrations.AddField(
            model_name='application',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobpostings.pipelinestage'),
        ),
    ]
