# Generated by Django 5.0 on 2025-11-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0008_pipelinestage_application_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(blank=True, help_text='List of skills required for this role (comma, semicolon, or newline separated)'),
        ),
    ]
